import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardLayout from "@/components/DashboardPage/DashboardLayout/DashboardLayout";
import ReduxProvider from "@/store/provider";
import { ToastContainer, ToastProvider } from "@/components/ui/toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ScoreLive Admin Panel",
  description: "Generated by scorelive admin group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <ReduxProvider>
            <DashboardLayout>
              {children}
            </DashboardLayout>
          </ReduxProvider>
          <ToastContainer />
        </ToastProvider>
      </body>
    </html>
  );
}
